spring.application.name=cadastropessoas
spring.datasource.url=jdbc:mysql://localhost:3306/cadastro_pessoas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true